---
- hosts: app
  become: True
  tasks:
  - name: Start the container
    docker_container:
        name: naveenapp
        image: "naveen023/sampleweb:{{BUILD_NUMBER}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
