# ---
# - hosts: app
#   become: True
#   tasks:
#   - name: Start the container
#     docker_container:
#         name: naveenapp
#         image: "naveen023/sampleweb:{{BUILD_NUMBER}}"
#         state: started
#         published_ports:
#           - 0.0.0.0:8080:8080
---
- hosts: app
  become: True
  tasks:
#     - name: Install python pip
#       yum:
#         name: python3-pip
#         state: present
#     - name: Install docker
#       yum:
#         name: docker
#         state: present
#     - name: start docker
#       service:
#         name: docker
#         state: started
#         enabled: yes
#     - name: Install docker-py python module
#       pip:
#         name: docker-py
#         state: present
#      - name: stopping existing containers
#        shell: docker container stop $(docker container ls -aq)
#      - name: removing the stopped containers
#        shell: docker container rm $(docker container ls -aq)
     - name: Start the container
       docker_container:
          name: facebooksample
          image: "naveen023/facebook:{{BUILD_NUMBER}}"
          state: started
          published_ports:
            - 0.0.0.0:8080:8080
